server:
  port: 8080
spring:
  application:
    name: admin
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: "@spring.datasource.driver@"
    url: "@spring.datasource.url@"
    username: "@spring.datasource.username@"
    password: "@spring.datasource.password@"
    test-while-idle: true
    max-wait-millis: 30000
    validation-query: 'SELECT 1'
    time-between-eviction-runs-millis: 20000
    min-evictable-idle-time-millis: 28700
    continue-on-error: true
    #data: classpath:dev/data.sql
  jpa:
    database-platform: "@spring.jpa.database-platform@"
    hibernate:
      ddl-auto: "@spring.jpa.hibernate.ddl-auto@"
    show-sql: "@spring.jpa.show-sql@"

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: docker
